import React from 'react';

export const Jp = {
	$$settings: {
		code: 'jp',
		name: '日本語',
		fallback: ''
	},
	// fix key, anything under PLAIN will not be proxy to other type
	// anything must be string, should be placed here.
	// such as input tooltip(string property), tuple name(not for react component)
	PLAIN: {
		NEW_DASHBOARD_NAME: 'ダッシュボード',
		DEFAULT_DASHBOARD_NAME: 'ダッシュボード',
		NEW_CONNECTED_SPACE_NAME: '連結空間',
		DEFAULT_CONNECTED_SPACE_NAME: '連結空間',
		NEW_SUBJECT_NAME: '主題',
		DEFAULT_SUBJECT_NAME: '主題',
		NEW_REPORT_NAME: 'レポート',
		DEFAULT_REPORT_NAME: 'レポート',
		CONSTANT_INPUT_PLACEHOLDER: '定数値を入力してください...',
		UNKNOWN_TOPIC_NAME: '不明なトピック',
		UNKNOWN_FACTOR_NAME: '不明なファクター',
		REPORT_DESCRIPTION_PLACEHOLDER: '説明を入力してください...',
		REPORT_DATASET_GRID_TITLE: 'レポートのデータセット',
		REPORT_DATASET_GRID_CLOSE: '閉じる',
		REPORT_DATASET_GRID_REFRESH: '更新',
		REPORT_DATASET_GRID_DOWNLOAD: 'ダウンロード'
	},
	ERROR: {
		UNAUTHORIZED: '権限がありません。ログインしてください。',
		ACCESS_DENIED: 'アクセスが拒否されました。詳細については、管理者にお問い合わせください。',
		UNPREDICTED: '未知のエラーが発生しました。詳細については、管理者にお問い合わせください。'
	},
	ALERT: {
		BUTTON: '取得',
		NOT_IMPLEMENT: '該当機能はまだ実装されていません。'
	},
	DIALOG: {
		BUTTON_YES: 'はい',
		BUTTON_NO: 'いいえ'
	},
	ACTIONS: {
		COPY: 'コピー',
		CLOSE: '閉じる',
		CANCEL: '取消',
		DELETE: '削除',
		CONFIRM: '確認',
		NEXT: '次へ',
		SORT_ASC: '昇順',
		SORT_DESC: '降順',
		PREVIOUS_PAGE: '前へ',
		NEXT_PAGE: '次へ',
		EXPAND: '展開じる',
		COLLAPSE: '閉じる',
		MINIMIZE: '最小化する',
		MAXIMIZE: '最大化する',
		RESTORE: '戻す'
	},
	LOGIN: {
		PRODUCT_TITLE: <>Indexical Metrics <span>&</span> Measure Advisory</>,
		MORNING: 'おはようございます ！',
		AFTERNOON: 'こんにちは ！',
		EVENING: 'こんばんは ！',
		BUTTON: 'ログイン ！',
		NAME_EMPTY: 'アカウントを入力してください。',
		CREDENTIAL_EMPTY: 'パスワードを入力してください。',
		FAIL: 'アカウントまたはパスワードの認証に失敗しました。'
	},
	CONSOLE: {
		LOADING: '個人データ読み込み中...',
		BYE: '終了しますか？',
		ERROR: {
			DASHBOARD_NOT_FOUND: '該当ダッシュボードが見つかりません。',
			CONNECTED_SPACE_NOT_FOUND: '該当連結空間が見つかりません。',
			SUBJECT_NOT_FOUND: '該当主題が見つかりません。',
			REPORT_NOT_FOUND: '該当レポートが見つかりません。'
		},
		MENU: {
			TITLE: 'Watchmenコンソール',
			HOME: 'ホーム',
			DASHBOARDS: 'ダッシュボード',
			FAVORITE: 'お気に入りを表示する',
			NOTIFICATIONS: '通知',
			MAILS: '受信トレイ',
			TIMELINE: 'タイムラインを表示する',
			CONNECT_SPACE: '連結空間に接続',
			SETTINGS: '設定',
			TO_ADMIN: '管理者に切り替える',
			TO_DATA_QUALITY: 'データ品質センターに切り替える'
		},
		FAVORITE: {
			TITLE: 'お気に入り',
			NO_DATA: 'お気に入りのアイテムはありません。',
			PIN: '固定',
			UNPIN: '固定を解除する',
			REMOVE: 'お気に入りから削除'
		},
		HOME: {
			TITLE: 'ホーム',
			SORT_BY_NAME: '名前で並べ替え',
			SORT_BY_VISIT_TIME: '訪問時間で並べ替え',
			VIEW_COLLAPSE: '折りたたむ',
			VIEW_ALL: '表示',
			CONNECTED_SPACE_TITLE: '接続された連結空間',
			CREATE_CONNECTED_SPACE_BUTTON: '連結空間に接続',
			DASHBOARD_TITLE: 'ダッシュボード',
			CREATE_DASHBOARD_BUTTON: 'ダッシュボードを作成する'
		},
		DASHBOARD: {
			SHARE: '共有',
			PRINT: 'プリント',
			REFRESH: '更新',
			AUTO_REFRESH: '自動更新(5分間隔)',
			ADD_INTO_FAVORITE: 'お気に入りに追加',
			REMOVE_FROM_FAVORITE: 'お気に入りから削除',
			ADD_REPORT: 'レポートを追加する',
			ADD_PARAGRAPH: 'コメントを追加する',
			ADD_DASHBOARD: 'ダッシュボードを追加する',
			SWITCH_DASHBOARD: 'ダッシュボードを切り替える',
			DELETE_ME: '削除',
			SHARE_DIALOG_LABEL: 'URLをコピーして共有する。',
			URL_COPIED: 'URLをコピーしました。',
			DELETE_DIALOG_LABEL: 'ダッシュボードを削除してもよろしいですか？ 削除したものは復元できませんので、ご注意ください。',
			NO_MORE_DASHBOARD: 'これ以上のダッシュボードは存在しません。',
			SWITCH_DIALOG_LABEL: 'ダッシュボードを選択してください',
			NO_MORE_REPORT: 'これ以上のレポートはありません。',
			DELETE_REPORT_DIALOG_LABEL: 'レポートを削除してもよろしいですか？ 削除したものは復元できませんので、ご注意ください。',
			DELETE_PARAGRAPH_DIALOG_LABEL: 'コメントを削除してもよろしいですか？ 削除したものは復元できませんので、ご注意ください。',
			NO_REPORT: 'レポートは定義されていません。',
			SHOW_PRINT_PAGE: 'ページサイズを表示する',
			HIDE_PRINT_PAGE: 'ページサイズを非表示する',
			SET_AS_ADMIN_HOME: '管理者ホームとして設定する'
		},
		CONNECTED_SPACE: {
			CATALOG: 'カタログ',
			SUBJECT_DEF: '主題を定義する',
			SUBJECT_DATA: 'データセット',
			SUBJECT_REPORT: 'レポート',
			REPORT_DATA: 'データセット',
			SHARE: '共有',
			PRINT: 'プリント',
			REFRESH: '更新',
			AUTO_REFRESH: '自動更新(5分間隔)',
			SHOW_PRINT_PAGE: 'ページサイズを表示する',
			HIDE_PRINT_PAGE: 'ページサイズを非表示する',
			DOWNLOAD_PAGE: 'このページをダウンロードする',
			DOWNLOAD_ALL: 'すべてをダウンロードする',
			ADD_REPORT: 'レポートを追加する',
			ADD_SUBJECT: '主題を追加する',
			OPEN_SUBJECT: '主題を開く',
			ADD_CONNECTED_SPACE: '連結空間に接続',
			SWITCH_CONNECTED_SPACE: '接続された連結空間に切り替える',
			DELETE_ME: '削除',
			ADD_INTO_FAVORITE: 'お気に入りに追加',
			REMOVE_FROM_FAVORITE: 'お気に入りから削除',
			SET_AS_TEMPLATE: 'テンプレートとして設定',
			REMOVE_FROM_TEMPLATE: 'テンプレートから削除',
			DELETE_DIALOG_LABEL: '連結空間を削除してもよろしいですか？ 削除したものは復元できませんので、ご注意ください。',
			NO_MORE_CONNECTED_SPACE: 'これ以上の接続された連結空間は存在しません。',
			SWITCH_DIALOG_LABEL: '接続された連結空間を選択してください',
			CREATE_DIALOG_LABEL: '利用可能な連結空間を選択してください',
			CREATE_DIALOG_CHOOSE_TEMPLATE_LABEL: '好きなテンプレートを選択してください',
			TEMPLATE: 'テンプレート',
			TEMPLATE_CREATE_BY: '著者',
			NO_MORE_SPACE: '連結空間がありません。詳細については、管理者に問い合わせてください。',
			SPACE_NOT_FOUND: '連結空間の定義が見つかりません。詳細については、管理者に問い合わせてください。',
			TOPICS_NOT_FOUND: 'トピックの定義が見つかりません。詳細については、管理者に問い合わせてください。',
			TOPICS_COUNT_MISMATCH: 'トピック数は一致していません。詳細については、管理者に問い合わせてください。',
			TOPIC_WITH_NO_FACTOR: 'ファクターは定義されていません。詳細については、管理者に問い合わせてください。',
			DELETE_SUBJECT_DIALOG_LABEL: '主題を削除してもよろしいですか？ 削除したものは復元できませんので、ご注意ください。',
			SWITCH_SUBJECT: '主題を切り替える',
			SWITCH_SUBJECT_DIALOG_LABEL: '主題を選択してください',
			NO_MORE_SUBJECT: 'これ以上の主題は存在しません。',
			SUBJECT_DEF_INVALID: '主題の定義に誤りがあります。確認してください。',
			SUBJECT_PICK_TOPICS: 'トピックを選択する',
			SUBJECT_DEFINE_COLUMNS: 'カラムを定義する',
			SUBJECT_FILTER_DATA: 'データフィルタ',
			SUBJECT_SET_JOINS: 'データ結合を設定する',
			SUBJECT_DEF_OVERVIEW: '一覧',
			NO_PICKED_TOPIC_FOR_SUBJECT: '選択されたトピックはありません。',
			NO_DATASET_COLUMN_FOR_SUBJECT: 'カラムは定義されていません。定義しますか',
			CREATE_DATASET_COLUMN_WHEN_NONE: '始める',
			NO_DATASET_COLUMN_FOR_SUBJECT_2: 'か？',
			ALIAS: 'カラム名',
			ADD_SUBJECT_COLUMN: 'カラムを追加する',
			CAN_NOT_DELETE_CHILD_FROM_COMPUTED: 'パラメータ数の最小限に達したため、削除できません。',
			CAN_NOT_ADD_CHILD_INTO_COMPUTED: 'パラメータ数の最大限に達したため、これ以上追加できません。',
			ADD_COMPUTE_PARAMETER: 'パラメータを追加する',
			NO_DATASET_FILTER_FOR_SUBJECT: 'フィルタは定義されていません。定義しますか',
			CREATE_DATASET_FILTER_WHEN_NONE: '始める',
			NO_DATASET_FILTER_FOR_SUBJECT_2: 'か？',
			ADD_SUBJECT_SUB_EXPRESSION_FILTER: 'フィルタの条件を追加する',
			ADD_SUBJECT_SUB_JOINT_FILTER: 'サブ結合を追加する',
			NO_DATASET_JOIN_FOR_SUBJECT: '結合は定義されていません。定義しますか',
			CREATE_DATASET_JOIN_WHEN_NONE: '始める',
			NO_DATASET_JOIN_FOR_SUBJECT_2: 'か？',
			ADD_SUBJECT_JOIN: '結合を追加する',
			SUBJECT_SELECT: 'Select',
			SUBJECT_NO_SELECT: 'カラムは定義されていません。',
			SUBJECT_FROM: 'From',
			SUBJECT_NO_FROM: '結合は定義されていません。',
			SUBJECT_JOIN_INNER: 'Inner Join',
			SUBJECT_JOIN_LEFT: 'Left Join',
			SUBJECT_JOIN_RIGHT: 'Right Join',
			SUBJECT_JOIN_ON: 'On',
			SUBJECT_JOIN_EQUALS: '=',
			SUBJECT_JOIN_AND: 'And',
			SUBJECT_WHERE: 'Where',
			SUBJECT_NO_WHERE: 'フィルタは定義されていません。',
			SUBJECT_UNKNOWN_PARAMETER: '不明なパラメータ',
			SUBJECT_EMPTY_CONSTANT: '空の定数値',
			SUBJECT_COLUMN_AS: 'As',
			SUBJECT_NO_ALIAS: '?',
			SUBJECT_FILTER_JOINT_NO_STATEMENT: 'ジョイントがありません',
			SUBJECT_UNKNOWN_FILTER: '不明なフィルタ',
			NO_DATASET_COLUMN: 'カラムは定義されていません。',
			UNFIX_COLUMN: 'これ以降のカラムの固定を解除すうｒ',
			FIX_COLUMN: 'このカラムに固定する',
			COMPRESS_COLUMNS: 'カラムの幅を狭める',
			NO_REPORT: 'レポートは定義されていません。定義しますか',
			CREATE_REPORT: '始める',
			NO_REPORT_2: 'か？',
			NO_MORE_REPORT: 'これ以上のレポートは存在しません.',
			SWITCH_REPORT: 'レポートを切り替える',
			SWITCH_REPORT_DIALOG_LABEL: 'レポートを選択してください',
			DELETE_REPORT_DIALOG_LABEL: 'レポートを削除してもよろしいですか？ 削除したものは復元できませんので、ご注意ください。',
			COLLAPSE_REPORT_SETTINGS_SECTIONS: 'すべてのセクションを折りたたむ',
			EXPAND_REPORT_SETTINGS_SECTIONS: 'すべてのセクションを表示する'
		},
		SETTINGS: {
			TITLE: '設定',
			LANGUAGE: '言語',
			THEME: 'テーマ',
			THEME_LIGHT: '標準',
			THEME_DARK: 'ダーク',
			PAT: {
				TITLE: 'パーソナルアクセストークン',
				CREATE: '新しいトークンを生成する',
				DESCRIPTION: 'Watchmen APIへのアクセスに使用できる生成したトークン。',
				DELETE_CONFIRM: 'トークンを削除してもよろしいですか？ 削除したものは復元できませんので、ご注意ください。',
				INPUT_PLACEHOLDER: 'トークンの目的を特定するためのメモ',
				NOTE_REQUIRED: 'トークンには注意が必要です。'
			}
		}
	},
	PARAM: {
		FROM: 'から',
		FROM_TOPIC: 'トピック',
		FROM_CONSTANT: '定数値',
		FROM_COMPUTED: '計算'
	},
	FACTOR: {
		SEQUENCE: 'シーケンス',
		NUMBER: '数値',
		UNSIGNED: '符号なし数値',
		TEXT: 'テキスト',
		ADDRESS: 'アドレス',
		CONTINENT: '大陸',
		REGION: '地域',
		COUNTRY: '国',
		PROVINCE: '州/省',
		CITY: '市',
		DISTRICT: '区',
		ROAD: '道',
		COMMUNITY: 'コミュニティ',
		FLOOR: '階',
		RESIDENCE_TYPE: '住宅タイプ',
		RESIDENTIAL_AREA: '住宅面積',
		EMAIL: 'メール',
		PHONE: '電話番号',
		MOBILE: '携帯番号',
		FAX: 'ファックス',
		DATETIME: '日付時刻',
		DATE: '日付',
		FULL_DATETIME: '日付(ミリ秒)',
		TIME: '時刻',
		YEAR: '年',
		HALF_YEAR: '上半期/下半期',
		QUARTER: '四半期',
		SEASON: '季節',
		MONTH: '月',
		HALF_MONTH: '月の上半期/月の下半期',
		TEN_DAYS: '上旬/中旬/下旬',
		WEEK_OF_YEAR: '年の週',
		WEEK_OF_MONTH: '月の週',
		HALF_WEEK: '週の上半期/週の下半期',
		DAY_OF_MONTH: '月の日',
		DAY_OF_WEEK: '週の日',
		DAY_KIND: '勤務日/週末/祝日',
		HOUR: '時間',
		HOUR_KIND: '勤務時間/勤務時間外/睡眠時間',
		MINUTE: '分',
		SECOND: '秒',
		MILLISECOND: 'ミリ秒',
		AM_PM: '午前/午後',
		GENDER: '性別',
		OCCUPATION: '職業',
		DATE_OF_BIRTH: '生年月日',
		AGE: '年齢',
		ID_NO: 'ID',
		RELIGION: '宗教',
		NATIONALITY: '国籍',
		TRADE: '業界',
		SCALE: '規模',
		BOOLEAN: 'ブール値',
		ENUM: '列挙',
		OBJECT: 'オブジェクト',
		ARRAY: 'アレイ'
	},
	PARAMETER: {
		EXPRESSION: '式',
		COMPUTE_TYPE: {
			NONE: 'As is',
			ADD: 'たす',
			SUBTRACT: 'ひく',
			MULTIPLY: 'かける',
			DIVIDE: 'わる',
			MODULUS: 'モジュロ',
			YEAR_OF: '年',
			HALF_YEAR_OF: '上半期/下半期',
			QUARTER_OF: '四半期',
			MONTH_OF: '月',
			WEEK_OF_YEAR: '年の週',
			WEEK_OF_MONTH: '月の週',
			DAY_OF_MONTH: '月の日',
			DAY_OF_WEEK: '週の日',
			CASE_THEN: 'ケース'
		},
		EXPRESSION_OPERATOR: {
			EMPTY: '空',
			NOT_EMPTY: '値がある',
			EQUALS: 'イコール',
			NOT_EQUALS: '不等',
			LESS: '未満',
			LESS_EQUALS: '以下',
			MORE: '超',
			MORE_EQUALS: '以上',
			IN: 'In',
			NOT_IN: 'Not In'
		}
	},
	JOINT: {
		AND: 'And',
		OR: 'OR'
	},
	JOIN: {
		INNER: '完全に一致',
		LEFT: '左側優先',
		RIGHT: '右側優先'
	},
	PAGINATION: {
		TOTAL: '合計',
		ROWS: '行',
		OF_PAGES: '/',
		PAGES: 'ページ'
	},
	CHART: {
		SETTINGS_HEADER_LABEL: 'レポート設定',
		SECTION_TITLE_BASIC_STYLE: '基本スタイル',
		SECTION_TITLE_DIMENSIONS: 'ディメンション',
		SECTION_TITLE_INDICATORS: '指標',
		NAME: '名称',
		DESCRIPTION: '説明',
		WIDTH: '幅',
		HEIGHT: '高さ',
		PIXEL: 'PX',
		DEGREE: '度',
		LINE_COLOR: '線の色',
		LINE_STYLE: '線のスタイル',
		FONT_FAMILY: '字体',
		FONT_COLOR: 'フォントの色',
		FONT_SIZE: 'フォントのサイズ',
		FONT_STYLE: 'フォントのスタイル',
		FONT_STYLE_NORMAL: '標準',
		FONT_STYLE_ITALIC: 'イタリック',
		FONT_WEIGHT: 'フォントの太さ',
		FONT_WEIGHT_100: '100',
		FONT_WEIGHT_200: '200',
		FONT_WEIGHT_300: '300',
		FONT_WEIGHT_400: '400',
		FONT_WEIGHT_500: '500',
		FONT_WEIGHT_600: '600',
		FONT_WEIGHT_700: '700',
		FONT_WEIGHT_800: '800',
		FONT_WEIGHT_900: '900',
		BACKGROUND_COLOR: '背景色',
		BORDER_STYLE: 'ボーダースタイル',
		BORDER_STYLE_NONE: 'なし',
		BORDER_STYLE_SOLID: 'ソリッド',
		BORDER_STYLE_DASHED: '破線',
		BORDER_STYLE_DOTTED: '点線',
		BORDER_COLOR: 'ボーダー色',
		BORDER_WIDTH: 'ボーダー幅',
		BORDER_RADIUS: 'ボーダー半径',
		POSITION: 'ポジション',
		POSITION_TOP: '上側',
		POSITION_RIGHT: '右側',
		POSITION_LEFT: '左側',
		POSITION_BOTTOM: '下側',
		ALIGNMENT: '水平方向に整列',
		ALIGNMENT_AUTO: 'オート',
		ALIGNMENT_LEFT: '左揃え',
		ALIGNMENT_CENTER: '中央揃え',
		ALIGNMENT_RIGHT: '右揃え',
		VERTICAL_ALIGNMENT: '垂直方向に整列',
		VERTICAL_ALIGNMENT_AUTO: 'オート',
		VERTICAL_ALIGNMENT_TOP: '上揃え',
		VERTICAL_ALIGNMENT_MIDDLE: '中央揃え',
		VERTICAL_ALIGNMENT_BOTTOM: '下揃え',
		TITLE_TEXT_ITEM_GAP: 'タイトルの間隔',
		PADDING: '余白',
		SHOW: '表示',
		LEGEND_ORIENT: '方向',
		LEGEND_ORIENT_HORIZONTAL: '水平',
		LEGEND_ORIENT_VERTICAL: '垂直',
		GRID_CONTAIN_LABEL: 'コンテナラベル',
		AXIS_TYPE: '軸タイプ',
		AXIS_TYPE_CATEGORY: 'カテゴリー',
		AXIS_TYPE_VALUE: '値',
		AXIS_TYPE_TIME: '時間',
		AXIS_AUTO_MIN: '（オート）最小値',
		AXIS_MIN: '最小値',
		AXIS_AUTO_MAX: '（オート）最大値',
		AXIS_MAX: '最大値',
		AXIS_NAME_LOCATION: 'ロケーション',
		AXIS_NAME_LOCATION_START: '開始',
		AXIS_NAME_LOCATION_CENTER: '中央',
		AXIS_NAME_LOCATION_END: '末尾',
		AXIS_NAME_GAP: '間隔',
		AXIS_NAME_ROTATE: '回転度',
		AXIS_LABEL_INSIDE: '内側',
		LABEL_GAP: '間隔',
		LABEL_ROTATE: '回転度',
		LABEL_FORMAT_USING_GROUP: '小数第3位',
		LABEL_FORMAT_USING_PERCENTAGE: '%を追加する',
		LABEL_VALUE_AS_PERCENTAGE: '値を%に変換する',
		LABEL_FRACTION_DIGITS: '小数位',
		LABEL_POSITION_TOP: '上側',
		LABEL_POSITION_LEFT: '左側',
		LABEL_POSITION_RIGHT: '右側',
		LABEL_POSITION_BOTTOM: '下側',
		LABEL_POSITION_INSIDE: '内部',
		LABEL_POSITION_INSIDE_LEFT: '内部の左側',
		LABEL_POSITION_INSIDE_RIGHT: '内部の右側',
		LABEL_POSITION_INSIDE_TOP: '内部の上側',
		LABEL_POSITION_INSIDE_BOTTOM: '内部の下側',
		LABEL_POSITION_INSIDE_TOP_LEFT: '内部の左上側',
		LABEL_POSITION_INSIDE_BOTTOM_LEFT: '内部の左下側',
		LABEL_POSITION_INSIDE_TOP_RIGHT: '内部の右上側',
		LABEL_POSITION_INSIDE_BOTTOM_RIGHT: '内部の右下側',
		LABEL_POSITION_OUTSIDE: '外部',
		LABEL_POSITION_CENTER: '中央',
		DECAL: 'デカール',
		ROAM: 'ローミング',
		TREE_LAYOUT: 'レーアウト',
		TREE_LAYOUT_ORTHOGONAL: '直交',
		TREE_LAYOUT_RADIAL: 'ラジアル',
		TREE_ORIENT: '方向',
		TREE_ORIENT_LEFT_RIGHT: '左から右へ',
		TREE_ORIENT_RIGHT_LEFT: '右から左へ',
		TREE_ORIENT_TOP_BOTTOM: '上から下へ',
		TREE_ORIENT_BOTTOM_TOP: '下から上へ',
		PIE_CENTER_X: '中央X',
		PIE_CENTER_Y: '中央Y',
		PIE_INSIDE_RADIUS: '内側の半径',
		PIE_OUTSIDE_RADIUS: '外側の半径',
		PIE_ROSE_TYPE: 'ローズ',
		PIE_ROSE_TYPE_NONE: 'なし',
		PIE_ROSE_TYPE_RADIUS: '半径により',
		PIE_ROSE_TYPE_AREA: '面積により',
		PIE_SHOW_PERCENTAGE: '%表示',
		PIE_LABEL_ALIGN_TO_NONE: 'なし',
		PIE_LABEL_ALIGN_TO_LABEL_LINE: 'ラベルライン',
		PIE_LABEL_ALIGN_TO_EDGE: '縁',
		MAP_REGION: '地域',
		MAP_REGION_JAPAN_L1: '日本 (県/都/府)',
		MAP_REGION_USA_L1: '米国 (州)',
		TRUNCATION_TYPE: 'タイプ',
		TRUNCATION_NONE: 'なし',
		TRUNCATION_TOP: '最高',
		TRUNCATION_BOTTOM: '最低',
		TRUNCATION_COUNT: '数量',
		BAR_TRANSFORM_AXIS: '軸の変換',
		LINE_SMOOTH: 'スムーズ',
		TOOLBOX_ORIENT: '方向',
		TOOLBOX_ORIENT_HORIZONTAL: '水平',
		TOOLBOX_ORIENT_VERTICAL: '垂直',
		SECTION_TITLE_COUNT_CHART: '特定スタイル',
		SECTION_TITLE_BAR_CHART: 'バー/ラインスタイル',
		SECTION_TITLE_PIE_CHART: 'パイスタイル',
		SECTION_TITLE_TREE_CHART: 'ツリースタイル',
		SECTION_TITLE_TREEMAP_CHART: 'ツリーマップスタイル',
		SECTION_TITLE_MAP_CHART: '地図スタイル',
		SECTION_TITLE_ECHART_TITLE: 'タイトル',
		SECTION_TITLE_ECHART_SUBTITLE: 'サブタイトル',
		SECTION_TITLE_ECHART_LEGEND: '凡例',
		SECTION_TITLE_ECHART_GRID: 'グリッド',
		SECTION_TITLE_ECHART_SERIES_LABEL: 'レベル',
		SECTION_TITLE_ECHART_XAXIS: 'X軸',
		SECTION_TITLE_ECHART_XAXIS_RANGE: 'X軸の範囲',
		SECTION_TITLE_ECHART_XAXIS_NAME: 'X軸の名称',
		SECTION_TITLE_ECHART_XAXIS_LABEL: 'X軸のレベル',
		SECTION_TITLE_ECHART_XAXIS_LINE: 'X軸の分割線',
		SECTION_TITLE_ECHART_XAXIS_MINOR_LINE: 'X軸のマイナー分割線',
		SECTION_TITLE_ECHART_YAXIS: 'Y軸',
		SECTION_TITLE_ECHART_YAXIS_RANGE: 'Y軸の範囲',
		SECTION_TITLE_ECHART_YAXIS_NAME: 'Y軸の名称',
		SECTION_TITLE_ECHART_YAXIS_LABEL: 'Y軸のレベル',
		SECTION_TITLE_ECHART_YAXIS_LINE: 'Y軸の分割線',
		SECTION_TITLE_ECHART_YAXIS_MINOR_LINE: 'Y軸のマイナー分割線',
		SECTION_TITLE_TRUNCATION: 'データの切り捨て',
		SECTION_TITLE_TOOLBOX: 'ツールボックス',
		NONAME_COLUMN: 'ノーネームカラム',
		UNKNOWN_COLUMN_NAME: '不明なカラム',
		CAN_NOT_DELETE_DIMENSION: 'ディメンションの最小限に達したため、削除できません。',
		CAN_NOT_ADD_DIMENSION: 'ディメンションの最大限に達したため、これ以上追加できません。',
		CAN_NOT_DELETE_INDICATOR: '指標の最小限に達したため、削除できません。',
		CAN_NOT_ADD_INDICATOR: '指標の最大限に達したため、これ以上追加できません。',
		ADD_DIMENSION: 'ディメンションを追加する',
		ADD_INDICATOR: '指標を追加する',
		PLEASE_SELECT_DIMENSION: '...を選択してください',
		PLEASE_SELECT_INDICATOR: '...を選択してください',
		ARITHMETIC_NONE: 'デフォルト',
		ARITHMETIC_SUMMARY: '合計',
		ARITHMETIC_AVERAGE: '平均値',
		ARITHMETIC_COUNT: '数量',
		ARITHMETIC_MAX: '最大値',
		ARITHMETIC_MIN: '最小値',
		TYPE: 'タイプ',
		TYPES: {
			COUNT: '統計グラフ',
			BAR: 'ヒストグラム',
			LINE: '折れ線グラフ',
			SCATTER: '散布図',
			PIE: '円グラフ',
			DOUGHNUT: 'ドーナツグラフ',
			NIGHTINGALE: 'ナイチンゲールグラフ',
			SUNBURST: 'サンバースト図',
			TREE: '樹形図',
			TREEMAP: 'ツリーマップ',
			MAP: 'マップ'
		},
		COUNT: {
			FORMAT_USING_GROUP: '小数第3位'
		},
		ECHART: {
			TEXT: 'テキスト'
		}
	},
	SHARE: {
		NOTHING: '内容が見つかりません。詳細については、管理者にお問い合わせください。'
	}
};